package back.cards.events;

public enum EventEnum {
    PRISONER(2), DESERTED_CAMP(3), ATTACK(3), JERRYCAN(1), ATTACK_BY_THE_OTHERS(2), GIFT(2), CHARITY(2),
    STARVING_CROCODILE(2), RAINMAKING(2), BANNED_PLACE(1), PLANE_OF_THE_OTHERS(1), HAPPY_BIRTHDAY(1), LOGGER(3),
    POTATO_CROP(2), CAREER_CHANGE(3), CRAZY_PSYCHIC(1), PRESTIGE_HOSTAGE(3), LOOTING(3), SECRET_STASH(3), MOULD(2),
    MARKET_DAY(1), ARMED_THREAT(1), BODY_ARMOUR(3), TRIBAL_CEMETERY(1), RUMBLING_VOLCANO(3), HEAVY_SWELL(2), BARTER(1),
    NEW_FRIEND(3), HEALER(2), INSULAR_TAX(1);

    int eventType;

    EventEnum(int eventType) {
        this.eventType = eventType;
    }

}
