import java.util.*;

public class Strings extends ListResourceBundle {
    public Object[][] getContents() {
        return contents;
    }

    private Object[][] contents = { { "hidden_card_label", "Card !" }, { "not_chief_label", "     " },
            { "chief_label", "Chief" }, { "AlarmClock_name", "Alarm Clock" }, { "AlarmClock_description", "" },
            { "Antivenom_name", "Anti-venom" }, { "Antivenom_description", "Anti-venom" }, { "Axe_name", "Axe" },
            { "Axe_description", "" }, { "Barometer_name", "Barometer" }, { "Barometer_description", "" },
            { "BoardGameQuoridor_name", "Board Game Quoridor" }, { "BoardGameQuoridor_description", "" },
            { "Cartridge_name", "Cartridge" }, { "Cartridge_description", "" }, { "Club_name", "Club" },
            { "Club_description", "" }, { "Coconut_name", "Coconut" }, { "Coconut_description", "" },
            { "Coffee_name", "Coffee" }, { "Coffee_description", "" }, { "Conch_name", "Conch" },
            { "Conch_description", "" }, { "CrystalBall_name", "Crystal Ball" }, { "CrystalBall_description", "" },
            { "FishingRod_name", "Fishing Rod" }, { "FishingRod_description", "" }, { "Flashlight_name", "Flashlight" },
            { "Flashlight_description", "" }, { "GiftBasket_name", "Gift Basket" }, { "GiftBasket_description", "" },
            { "Gourd_name", "Gourd" }, { "Gourd_description", "" }, { "Gun_name", "Gun" }, { "Gun_description", "" },
            { "KitBBQCannibal_name", "Kit BBQ Cannibal" }, { "KitBBQCannibal_description", "" },
            { "LuxuryCarKey_name", "Luxury Car Key" }, { "LuxuryCarKey_description", "" },
            { "Matches_name", "Matches" }, { "Matches_description", "" }, { "MetalSheet_name", "Metal Sheet" },
            { "MetalSheet_description", "" }, { "OldBrief_name", "Old Brief" }, { "OldBrief_description", "" },
            { "Pendulum_name", "Pendulum" }, { "Pendulum_description", "" }, { "RottenFish_name", "Rotten Fish" },
            { "RottenFish_description", "" }, { "Sandwich_name", "Sandwich" }, { "Sandwich_description", "" },
            { "Sardines_name", "Sardines" }, { "Sardines_description", "" }, { "SleepingPills_name", "Sleeping Pills" },
            { "SleepingPills_description", "" }, { "Spyglass_name", "Spyglass" }, { "Spyglass_description", "" },
            { "StagnantWater_name", "Stagnant Water" }, { "StagnantWater_description", "" },
            { "ToiletBrush_name", "Toilet Brush" }, { "ToiletBrush_description", "" },
            { "VegetableMill_name", "Vegetable Mill" }, { "VegetableMill_description", "" },
            { "VoodooDoll_name", "Voodoo Doll" }, { "VoodooDoll_description", "" },
            { "WaterBottle_name", "Water Bottle" }, { "WaterBottle_description", "description water bottle" },
            { "WinningLotteryTicket_name", "Winning Lottery Ticket" }, { "WinningLotteryTicket_description", "" },
            { "WoodenPlank_name", "Wooden Plank" }, { "WoodenPlank_description", "Adds one place on the raft." },
            { "player_name", "Player" }, { "yesNoQuestion", "(y/n)" },
            { "wouldLikePlayCard?", "Would like to play a card ?" }, { "cardsDisplay", "Your cards are : " },
            { "invalidChoice", "Invalid choice !" }, { "chooseACard", "Choose a card with its index" },
            { "choiceResult", "You choose " }, { "cannotPlayCard", "You cannot play this card now !" },
            { "choosePlayerList", "Choose a player in this list : " },
            { "chooseActionList", "Choose an action in this list : " },
            { "howManyFragments", "How many plank fragments would you like to get ?" },
            { "gotFood", "Food rations acquired : " }, { "gotWater", "Water rations acquired : " },
            { "gotWood", "Plank fragments acquired : " }, { "gotCard", " got a card" },
            { "playerGotSick", " got sick !" }, { "decideWhoDie", "Someone has to die. Choose one player." },
            { "decideWhoVote", "Someone has to die. Vote for one player." }, { "votesFor", " votes for " },
            { "nextWeather", "The next two weather : " }, { "cardsOfAllPlayers", "The cards of all players : " },
            { "nextCards", "The next cards in the deck : " },
            { "sickNowCuredPlayer", " was sick and could not play, now cured" }, { "playerTurn", "'s turn !" },
            { "isSickPlayer", " is sick and cannot play !" }, { "isDeadPlayer", " is dead and cannot play !" },
            { "distributionTime", "It is time to distribute the rations of the round !" },
            { "distributionEnd", "Distribution ended !" }, { "allPlayersDead", "All players are dead !" },
            { "hurricane", "Hurricane !" }, { "volontaryDeparture", "Volontary Departure !" },
            { "newRoundInit", "It is a new day !" }, { "endGame", "End of the game!" },
            { "fooAction", " is getting food !" }, { "waterAction", " is getting water !" },
            { "woodAction", " is getting wood !" }, { "cardAction", " is getting a card !" },
            { "playAgain", " will play again !" }, { "votingTwice", " will be voting twice, thanks to his club" },
            { "designatedPlayer", " is designated by the crew" },
            { "chiefWillDecide", "The chief will decide who will be sacrificied" },
            { "sacrificedForCrew", " has been sacrificed for the sake of the crew :(" },
            { "cardsOfPlayersSpyglass", "The cards of the players : " }, { "hasCard", " has the cards " },
            { "chooseAction", "Choose your action" }, { "notification", "Notification !" },
            { "choosePlayer", "Choose a player" }, { "chooseNbTries", "Choose your number of tries" },
            { "cardDescription", "Card Description" }, { "food", "Food" }, { "water", "Water" }, { "wood", "Wood" },
            { "card", "Card" }, { "next", "Next" }, { "beginVote", "Begin Vote" },
            { "confirmPlayer", "Confirm Designated Player" }, { "useCard", "Use the card" },
            { "hiddenCards", "Hidden Cards" }, { "revealedCards", "Revealed Cards" },
            { "woodPlanksFragment", "Wood Plank Fragments" }, { "woodPlanks", "Wood Planks" }, { "weather", "Weather" },
            { "alive", "Alive" }, { "round", "Round" }, { "currentPlayer", "Current Player" } };
}